services:
  register-service-web:
    container_name: register-service-web
    build: 
      context: ./docker/nginx
      args: 
        UID: 502
    ports:
      - 1000:80
    volumes: 
      - ./public:/appdata/www/public
